### ISSUE TITLE
🐛 BUG - GitHub Contributions not showing up

### ISSUE THREAD

**Issue by tiagov8** [SSWConsulting/SSW.People#435] opened 2022-09-16 18:56 UTC
cc @adamcogan 

Hi team,

I noticed the GitHub contributions widget is showing an "error :(" (looked at [Tiago's](https://www.ssw.com.au/people/tiago-araujo), [Adam's](https://www.ssw.com.au/people/adam-cogan), and [Uly's](https://www.ssw.com.au/people/uly))

1. Please investigate and fix

<img width="1070" alt="Screen Shot 2022-09-16 at 11 53 38 AM" src="https://user-images.githubusercontent.com/12601228/190711279-f3d6e65c-e903-40d4-913a-13d8e0230b29.png">

**Comment by bradystroud** [comment] 2022-09-29 12:17
Closing as this is a duplicate of #433

**Closed by bradystroud** 2022-09-29 12:17 UTC
